// Pure formatting functions — no side effects

function weekLabel(weekOf) {
  return new Date(weekOf).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function weekLabelShort(weekOf) {
  return new Date(weekOf).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
}

const CATEGORY_ORDER = ["Protein", "Dairy", "Carbs", "Vegetables", "Fats"];

export function formatPlainText(items, weekOf, macroTotals) {
  const included = items.filter((i) => i.included);
  const sep = "════════════════════════════════";
  const lines = [`GROCERY LIST — Week of ${weekLabel(weekOf)}`, sep, ""];

  CATEGORY_ORDER.forEach((cat) => {
    const catItems = included.filter((i) => i.category === cat);
    if (!catItems.length) return;
    lines.push(cat.toUpperCase());
    catItems.forEach((item) => {
      const name = `• ${item.name}`;
      const qty = `${item.qty}${item.unit}`;
      const dots = ".".repeat(Math.max(2, 36 - name.length - qty.length));
      lines.push(`${name} ${dots} ${qty}`);
    });
    lines.push("");
  });

  lines.push(sep);
  if (macroTotals) {
    lines.push(
      `Weekly macros: ${macroTotals.protein.toLocaleString()}g protein | ` +
        `${macroTotals.calories.toLocaleString()} kcal | ` +
        `${macroTotals.carbs.toLocaleString()}g carbs | ` +
        `${macroTotals.fat.toLocaleString()}g fat`
    );
  }
  lines.push("Generated by Macro Grocery Generator");
  return lines.join("\n");
}

const CATEGORY_EMOJI = {
  Protein: "💪",
  Dairy: "🥛",
  Carbs: "🌾",
  Vegetables: "🥦",
  Fats: "🥑",
};

export function formatWhatsApp(items, weekOf, macroTotals) {
  const included = items.filter((i) => i.included);
  const lines = [`🛒 *Grocery List — ${weekLabelShort(weekOf)}*`, ""];

  CATEGORY_ORDER.forEach((cat) => {
    const catItems = included.filter((i) => i.category === cat);
    if (!catItems.length) return;
    lines.push(`${CATEGORY_EMOJI[cat] ?? "•"} *${cat}*`);
    catItems.forEach((item) => lines.push(`☐ ${item.name} — ${item.qty}${item.unit}`));
    lines.push("");
  });

  if (macroTotals) {
    lines.push(
      `📊 ${macroTotals.protein.toLocaleString()}g protein | ${macroTotals.calories.toLocaleString()} kcal`
    );
  }
  lines.push("✅ = done | tap to copy & paste into chat");
  return lines.join("\n");
}

export function formatCSV(items, weekOf) {
  const header = `Item,Category,Qty,Unit,Calories,Protein (g),Carbs (g),Fat (g)`;
  const rows = items
    .filter((i) => i.included)
    .map((i) =>
      [
        `"${i.name}"`,
        i.category,
        i.qty,
        i.unit,
        i.macros.calories,
        i.macros.protein,
        i.macros.carbs,
        i.macros.fat,
      ].join(",")
    );
  return [header, ...rows].join("\n");
}

export function formatJSON(items, weekOf, weeklyMacros) {
  return JSON.stringify(
    {
      weekOf,
      exportedAt: new Date().toISOString(),
      weeklyMacros,
      items: items.filter((i) => i.included),
    },
    null,
    2
  );
}

export function formatShoppingChecklist(items) {
  return items
    .filter((i) => i.included)
    .map((i) => ({ name: i.name, qty: i.qty, unit: i.unit }))
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((i) => `□ ${i.name} ${i.qty}${i.unit}`)
    .join("\n");
}

export function getPrintHTML(items, weekOf, macroTotals) {
  const included = items.filter((i) => i.included);
  const leftCats = ["Protein", "Dairy"];
  const rightCats = ["Carbs", "Vegetables", "Fats"];

  function renderColumn(cats) {
    return cats
      .map((cat) => {
        const catItems = included.filter((i) => i.category === cat);
        if (!catItems.length) return "";
        const rows = catItems
          .map(
            (item) =>
              `<tr><td style="padding:3px 0">☐ ${item.name}</td><td style="text-align:right;padding:3px 0;padding-left:12px">${item.qty}${item.unit}</td></tr>`
          )
          .join("");
        return `<div style="margin-bottom:16px"><h3 style="font-size:12px;font-weight:700;letter-spacing:0.05em;margin:0 0 6px;text-transform:uppercase">${cat}</h3><table style="width:100%;font-size:13px">${rows}</table></div>`;
      })
      .join("");
  }

  const macroLine = macroTotals
    ? `${macroTotals.protein.toLocaleString()}g protein &nbsp;|&nbsp; ${macroTotals.calories.toLocaleString()} kcal &nbsp;|&nbsp; ${macroTotals.carbs.toLocaleString()}g carbs &nbsp;|&nbsp; ${macroTotals.fat.toLocaleString()}g fat`
    : "";

  return `<!DOCTYPE html><html><head><title>Grocery List — ${weekLabelShort(weekOf)}</title>
<style>
  body { font-family: -apple-system, sans-serif; color: #111; max-width: 700px; margin: 0 auto; padding: 24px; }
  h1 { font-size: 20px; margin: 0 0 2px; }
  .subtitle { font-size: 13px; color: #666; margin: 0 0 12px; }
  hr { border: none; border-top: 2px solid #111; margin: 10px 0 16px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
  .footer { margin-top: 20px; border-top: 2px solid #111; padding-top: 10px; font-size: 12px; color: #444; }
  @media print { button { display: none; } }
</style></head><body>
<h1>Grocery List</h1>
<p class="subtitle">Week of ${weekLabel(weekOf)}</p>
<hr/>
<div class="grid">
  <div>${renderColumn(leftCats)}</div>
  <div>${renderColumn(rightCats)}</div>
</div>
<div class="footer">${macroLine}</div>
<br/>
<button onclick="window.print()" style="padding:8px 16px;font-size:13px;cursor:pointer">🖨️ Print / Save as PDF</button>
</body></html>`;
}
